default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= "#{ENV.fetch("DB_NAME")}_development" %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: 20

test:
  <<: *default
  database: <%= "#{ENV.fetch("DB_NAME")}_test" %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>